name: Scott and Kat
favicon: null
layout_spectrum: 0.48831
typography_spectrum: 0.41013
title: 'Scott & Kat'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0f'
    - '#313e2a'
    - '#ffffff'
    - '#847f83'
    - '#b4c440'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
